CC=cc
CFLAGS= -ggdb -Wall
LDFLAGS= -lSDL2
SOURCES=chip8.c
OBJECTS=$(SOURCES:.cp=.o)
EXECUTABLE=bin/chip8

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $(LDFLAGS) $(OBJECTS) -o $@

